# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---

# Polypane releases are available at
# <https://github.com/firstversionist/polypane/releases/>.
polypane__polypane_package_checksum: 'sha256:e9771be74be0208b20a433cc88249ca4fc63294da6b5ce776dd6a073f7696d51'
polypane__polypane_version: '28.0.0'


# The following variables will have host-specific and/or sensitive
# values and must be defined elsewhere (in an inventory, playbook, at
# runtime, etc).

# A string containing the directory where downloaded files are stored to
# prevent unnecessary downloading when tasks are rerun.
polypane__download_cache_directory: '{{ undef() }}'
